### ISSUE TITLE
Out of map point when computing hPolys.

### ISSUE THREAD

**Issue by Chortine** [ZJU-FAST-Lab/Car-like-Robotic-swarm#13]
Hi Team,

I found out that when computing the hPolys for fine optimization, the case that point is out of map is allowed, and sometimes cause the final global path out of the map.

Shouldn't here be `map_ptr_->getVoxelState2d(tmp) != 0` to filter out the out of map points?

https://github.com/ZJU-FAST-Lab/Car-like-Robotic-swarm/blob/eabbf7c907babe450b49da88c204bf61bf6c1709/src/Minco/traj_planner/src/kino_astar.cpp#L260

**Comment by Leon-Redfield** [comment]
Yes you are right, it would be better if there is a filter to filter the out of map points
