### ISSUE TITLE
 I read the SD-VD section of your paper, but I can't find this condition of k △ s ≤ S in the code. Can you provide this condition to judge the position in the code? 

### ISSUE THREAD

**Issue by lyaruyyyyy** [ZJU-FAST-Lab/Car-like-Robotic-swarm#14]
Hello, I read the SD-VD section of your paper, but I can't find this condition of k △ s ≤ S in the code. Can you provide this condition to judge the position in the code? Thank you very much! Look forward to your reply!

**Comment by Leon-Redfield** [comment]
In the kinoastar.cpp file, line 510, you will see that `cur_node->number < 20` which means that k equals to 20.
