### ISSUE TITLE
run in real rover

### ISSUE THREAD

**Issue by FPSychotic** [ZJU-FAST-Lab/Car-like-Robotic-swarm#2]
hi, any chance to run this planner on real rover? I have the rover and it could run any planner as fuel, fast-planner, eva... is it possible run this with some light modification or launch file?

Thanks, specially great you made this for rovers, they looks a little forgotten lately against drones.

**Comment by Leon-Redfield** [comment]
Hi! Ideally, this code could be able to run on real rover. But you need to have your own controller and sensors such as lidar. But I still recommend reading the code carefully, and then modify some parameters depending on the situation of your own rover. For instance, if you have only one car to plan, remember to change the paramter in the launch file `<arg name="cars_num" value="8" /` and change this parameter to 1. Good luck
