### ISSUE TITLE
Hello, if the real car doesn't have NOKOV motion capture system, can lidar and imu be used instead?

### ISSUE THREAD

**Issue by 3oo0q-kvmlskz** [ZJU-FAST-Lab/Car-like-Robotic-swarm#3]
Hello, if the real car doesn't have NOKOV motion capture system, can lidar and imu be used instead?
 I look forward to your answer. Thank you very much.

**Comment by Leon-Redfield** [comment]
Definitely yes! The motion capture system is used to provide accurate odometry for planning. If you have other odometry algorithms or projects, it's completely feasible to replace the motion capture system. The reason why I used motion caputure system is that the computation platform on the car is weak which is difficult to run other odometry algorithms.
