### ISSUE TITLE
 Hello, I tried to run your code but found that three .h files are missing. May I ask if these three files are available to me?

### ISSUE THREAD

**Issue by lyaruyyyyy** [ZJU-FAST-Lab/Car-like-Robotic-swarm#4]
Hello, I tried to run your code but found that three .h files are missing. May I ask if these three files are available to me?

#include "kinematics_simulator/MincoTraj.h"
#include "kinematics_simulator/SingleMinco.h"
#include "kinematics_simulator/Trajectory.h"

**Comment by Leon-Redfield** [comment]
Hi! These files are the ros messages, and they are corresponding to the three messages in file `src/simulator/kinematics_simulator/msg`. Hence, I guess there's something wrong with the ros message compilation, and there are no specific .h files. Good luck

**Comment by bigdoubi** [comment]
Maybe you can try "catkin_make -DCMAKE_BUILD_TYPE=Release -j1" to compile your code?

**Comment by datasqr** [comment]
To compile the code follow the next steps:
* install additional libs: sudo apt-get install libompl-dev libgoogle-glog-dev -y
* comment code in 'kinematic_sim.cpp' leave only 'main' method: int main (int argc, char** argv) {return 0;}
* source /opt/ros/noetic/setup.bash
* run: catkin_make
* uncomment the code in kinematic_sim.cpp
* source devel/setup.bash
* run: catkin_make -DCMAKE_BUILD_TYPE=Release

**Comment by ZeeCarl** [comment]
if failed,try this: 
 add_dependencies(kinematics_simulator_node ${PROJECT_NAME}_generate_messages_cpp) 

add this to the bottom of CMakeLists.txt
