### ISSUE TITLE
Hello, excuse me, is the method of this paper applicable to scenarios involving other moving obstacles besides vehicle groups? Look forward to your reply, thank you very much!

### ISSUE THREAD

**Issue by 3oo0q-kvmlskz** [ZJU-FAST-Lab/Car-like-Robotic-swarm#5]
Hello, excuse me, is the method of this paper applicable to scenarios involving other moving obstacles besides vehicle groups? Look forward to your reply, thank you very much!

**Comment by Leon-Redfield** [comment]
Hi! This is a good question. If you want to run this project with other moving obstacles, you have to predict the moving obstacles and take the predicted motion into the speed planning and optimization. In this project, the trajectories of other agents are broadcast by the wireless network. But if other moving obstacles are involved, their trajectories can not be directly obtained. Hence, what you need to add is a motion prediction module to predict the trajectory of other moving obstacles.
