### ISSUE TITLE
MPC

### ISSUE THREAD

**Issue by Krasjet-Yu** [ZJU-FAST-Lab/Car-like-Robotic-swarm#7]
Can you provide the control code for mpc? I have implemented an MPC programme to control a gazebo robot and it seems that the robot does not track the trajectory of the planner.

**Comment by Leon-Redfield** [comment]
Sorry I'm not authoried to share the mpc controller by myself. Code of the mpc controller is mainly contributed by @GaoLon, you can contact him by email:  [gaolon@zju.edu.cn](url)   for more details.
